pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "anidubonline/cicd"
        CONTAINER_NAME = "cicd-container"
        LOCAL_IMAGE_NAME = "local-cicd-image"
    }

    stages {
        stage('Clone repository') {
            steps {
                git branch: 'main', url: 'https://github.com/anidubonline/cicd.git', credentialsId: 'your-git-credentials'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}", "-f ci/Dockerfile .")
                }
            }
        }

        stage('Save Docker Image Locally') {
            steps {
                script {
                    docker.save("${LOCAL_IMAGE_NAME}.tar", "${DOCKER_IMAGE}")
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    // Загружаем сохраненный Docker-образ в локальное хранилище Docker
                    docker.load("-i ${LOCAL_IMAGE_NAME}.tar")
                    
                    // Удаляем существующий контейнер, если он существует
                    try {
                        sh "docker rm -f ${CONTAINER_NAME}"
                    } catch (Exception e) {
                        // Если контейнер не существует, игнорируем ошибку
                    }
                    
                    // Запускаем новый контейнер с загруженным образом
                    sh "docker run -d --name ${CONTAINER_NAME} -p 80:80 ${DOCKER_IMAGE}"
                }
            }
        }
    }
}
