pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "anidubonline/cicd"
        CONTAINER_NAME = "hello-world-nginx-container"
    }

    stages {
        stage('Clone repository') {
            steps {
                git 'https://github.com/anidubonline/cicd.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Собрать Docker-образ из Dockerfile
                    docker.build("${DOCKER_IMAGE}", "-f ci/Dockerfile .")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    // Отправить Docker-образ на Docker Hub
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                        docker.image("${DOCKER_IMAGE}").push()
                    }
                }
            }
        }

        stage('Stop and Remove Old Container') {
            steps {
                script {
                    def containerExists = sh(script: "docker ps -a --filter 'name=${CONTAINER_NAME}' --format '{{.Names}}'", returnStdout: true).trim()
                    if (containerExists) {
                        sh "docker rm -f ${CONTAINER_NAME}"
                    }
                }
            }
        }

        stage('Run New Container') {
            steps {
                script {
                    dockerImage.run("-d -p 80:80 --name ${CONTAINER_NAME}")
                }
            }
        }
    }
}
